# Generated by Django 4.2.5 on 2023-09-20 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0002_process_active'),
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=500, verbose_name='Observação do despacho')),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Data de despache')),
                ('from_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_from_sector', to='sector.sector', verbose_name='Setor que enviou o proesso')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='process.process', verbose_name='Processo')),
                ('to_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_to_sector', to='sector.sector', verbose_name='Setor que recebeu o processo')),
            ],
        ),
    ]
