# Generated by Django 4.2.5 on 2023-09-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='observation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Observação do despacho'),
        ),
    ]
