# Generated by Django 4.2.5 on 2023-09-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
        ('dispatch', '0002_alter_dispatch_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='from_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_from_sector', to='sector.sector', verbose_name='Setor que enviou o processo'),
        ),
    ]
