# Generated by Django 4.2.5 on 2023-09-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.CharField(max_length=255, verbose_name='Numero do Processo')),
                ('object', models.CharField(max_length=255, verbose_name='Objeto')),
                ('status', models.BooleanField(default=False, verbose_name='Recebido pela unidade?')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sector.sector', verbose_name='Setor')),
            ],
        ),
    ]
