# Generated by Django 4.2.5 on 2023-09-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Processo Ativo?'),
        ),
    ]
