# Generated by Django 4.2.5 on 2023-09-20 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
        ('process', '0002_process_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='_previous_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_sector', to='sector.sector', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='process',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_sector', to='sector.sector', verbose_name='Setor'),
        ),
    ]
