# Generated by Django 4.2.5 on 2023-09-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
        ('process', '0003_process__previous_sector_alter_process_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='_previous_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_sector', to='sector.sector'),
        ),
    ]
