# Generated by Django 4.2.5 on 2023-09-20 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process', '0004_alter_process__previous_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_fake', to=settings.AUTH_USER_MODEL),
        ),
    ]
