# Generated by Django 4.2.5 on 2023-09-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_process__user'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='_obs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
